### ISSUE TITLE
python3.7-nodejs14-slim tag is 3.7.10 not 3.7.11

### ISSUE THREAD

**Issue by PaulMonnery** [nikolaik/docker-python-nodejs#26]
Hi, thanks for these very usefull images!

I am currently facing an issue with the `python3.7-nodejs14-slim` tag. it is written on the README that the python version is `3.7.11`  but it is in fact python `3.7.10`, which breaks my poetry installation because of incompatible version with some packages :grimacing: 

```bash
$ docker run --rm -it nikolaik/python-nodejs:python3.7-nodejs14-slim python --version
Python 3.7.10
```

Is it a build step issue within the dockerfile or the readme is just not up to date?

EDIT: from `python-nodejs:python3.7-nodejs16-slim`, python version is indeed `3.7.11`

**Comment by nikolaik** [comment]
> Hi, thanks for these very usefull images!

I'm glad you find them useful! 🤗

> I am currently facing an issue with the `python3.7-nodejs14-slim` tag. it is written on the README that the python version is `3.7.11` but it is in fact python `3.7.10`, which breaks my poetry installation because of incompatible version with some packages 😬
> 
> ```shell
> $ docker run --rm -it nikolaik/python-nodejs:python3.7-nodejs14-slim python --version
> Python 3.7.10
> ```

What version of python do you get if you run `docker run --pull=always --rm -it nikolaik/python-nodejs:python3.7-nodejs14-slim python --version`? It could simply be because you have pulled the tag when the image was at pthon 3.7.10 and need to do it again to get on the latest and greatest.

If you want to pin the python version, you probably want to create your own image, since the tags are constantly evolving with new bugfix releases of python. If you just need the latest. You can run `docker pull` once in a while or give a little present of `--pull=always` to `docker run`.

**Comment by PaulMonnery** [comment]
Running `docker run --pull=always --rm -it nikolaik/python-nodejs:python3.7-nodejs14-slim python --version` solved the problem, thanks!
 
Indeed, I will maybe have to build my own images if it breaks on each new release :thinking: I'll see on next release then!

**Comment by nikolaik** [comment]
Glad it worked out!
