### ISSUE TITLE
Linux commands not available

### ISSUE THREAD

**Issue by hajimurtaza** [nikolaik/docker-python-nodejs#4]
Not able to run  commands like 'sudo' , 'zip'.
Can you provide a valid reason for that?
need to run aws cli and send zip file for aws deployment and lambda functions

**Comment by nikolaik** [comment]
The idea of this image was not to be general purpose with packages for a range of usages, but solve the common problem of web apps in python using node.js to build their frontend. Right now, we stick with whatever the debian images are installing through using the python base image and with node.js and yarn on top.

`sudo` is not needed, since we don't set a `USER` in the Dockerfile, thus defaulting to the root user.  Using `sudo` in docker is discouraged according to [docker docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user).

**Comment by nikolaik** [comment]
To solve your case, do `apt update && apt install zip -y` before installing aws-cli
